#!/bin/bash

# setups the virtual env environment
# ENSURE THIS IS CALLED IN THE PROJECT DIRECTORY
# for Archlinux
# pa -S python-virtualenv
# pa -S python-pip

skip=0
command virtualenv . 2>/dev/null ||\
	{ echo "Please install Python Virtualenv with your package manager first.";skip=1; }

echo $skip
if [ ${skip} = 0 ];then
	echo "Setting up virtualenv"
	. bin/activate
	pip3 install flask flask-admin flask-login flask-wtf flask-mail flask-socketio
	pip3 install paho-mqtt sqlalchemy gevent
	yes | ./reset.sh
	deactivate
fi
